services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SA"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1450:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./CriarBanco.sql:/tmp/CriarBanco.sql
      - ./init-sqlserver.sh:/tmp/init-sqlserver.sh
    command: /bin/bash ./tmp/init-sqlserver.sh